`use client`

import Header from "./Component/Header"
import Footer from "./Component/Footer";
import Button from "./Component/Buttom";
import { CartProvider } from './Component/CartContext';

import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <CartProvider>

          <Header />
          {children}
          <Footer />
          <Button />

        </CartProvider>



      </body>
    </html>
  );
}
